# -*- coding: utf-8 -*-
# Monuments/sites touristiques/spécialités locales, un par pays, trouvés par
# recherche (connaissances générales vérifiées + WebSearch pour les pays
# moins connus). Clé = tier. Valeur = (nom_court, description_complète).
# nom_court sert de réponse QCM (doit rester compact) ; description utilisée
# dans la question elle-même.

MONUMENTS = {
    0: ("le château de Neuschwanstein", "Château romantique du roi Louis II de Bavière, modèle du château de la Belle au Bois Dormant à Disneyland"),
    1: ("l'escudella", "Pot-au-feu traditionnel andorran (viandes, légumes, pâtes ou riz)"),
    2: ("Stonehenge", "Cercle de mégalithes préhistoriques du Wiltshire"),
    3: ("le monastère de Khor Virap", "Célèbre pour sa vue sur le mont Ararat"),
    4: ("le château de Schönbrunn", "Ancienne résidence d'été des Habsbourg à Vienne"),
    5: ("le Manneken-Pis", "Statuette bruxelloise en bronze d'un jeune garçon"),
    6: ("le monastère de Rila", "Plus grand monastère orthodoxe de Bulgarie"),
    7: ("la Petite Sirène", "Statue de bronze à Copenhague inspirée du conte d'Andersen"),
    8: ("le Loch Ness", "Lac écossais réputé pour sa légende du monstre « Nessie »"),
    9: ("la Sagrada Família", "Basilique inachevée de Gaudí à Barcelone"),
    10: ("la vieille ville de Tallinn", "Centre médiéval fortifié classé UNESCO"),
    11: ("le sauna", "Tradition ancestrale de bain de vapeur finlandaise"),
    12: ("la tour Eiffel", "Monument emblématique de Paris construit par Gustave Eiffel"),
    13: ("la vache Guernesey", "Race bovine réputée pour son lait très riche en crème"),
    14: ("le Parlement de Budapest", "Imposant édifice néogothique sur les rives du Danube"),
    15: ("les falaises de Moher", "Spectaculaires falaises côtières du comté de Clare"),
    16: ("le Colisée", "Amphithéâtre antique emblématique de Rome"),
    17: ("la Jersey Royal", "Variété de pomme de terre nouvelle originaire de l'île"),
    18: ("le Monument de la Liberté", "Colonne de granit à Riga, symbole de l'indépendance lettone"),

    19: ("le château de Trakai", "Forteresse médiévale de brique rouge sur une île du lac Galvė"),
    20: ("les Casemates du Bock", "Galeries souterraines fortifiées creusées dans le rocher"),
    21: ("le Casino de Monte-Carlo", "Célèbre casino et symbole du luxe monégasque"),
    22: ("le Geirangerfjord", "Fjord classé UNESCO entouré de falaises et de cascades"),
    23: ("les moulins de Kinderdijk", "19 moulins historiques du XVIIIe siècle utilisés pour drainer les polders"),
    24: ("le château de Caernarfon", "Forteresse médiévale, lieu d'investiture des princes de Galles"),
    25: ("le château du Wawel", "Résidence historique des rois de Pologne à Cracovie"),
    26: ("la tour de Belém", "Tour fortifiée du XVIe siècle à Lisbonne"),
    27: ("le château de Bran", "Forteresse des Carpates associée à la légende de Dracula"),
    28: ("le Kremlin", "Ancienne citadelle fortifiée de Moscou"),
    29: ("les Tre Torri du Mont Titano", "Trois forteresses médiévales, symbole national de Saint-Marin"),
    30: ("la forteresse de Belgrade (Kalemegdan)", "Citadelle historique au confluent de la Save et du Danube"),
    31: ("le château de Bratislava", "Forteresse aux quatre tours dominant le Danube"),
    32: ("le lac de Bled", "Lac alpin avec sa petite île et son château médiéval"),
    33: ("le Vasa", "Navire de guerre suédois du XVIIe siècle, coulé puis conservé au musée de Stockholm"),
    34: ("le Cervin (Matterhorn)", "Montagne emblématique des Alpes suisses près de Zermatt"),
    35: ("le château de Prague", "Plus vaste complexe castral ancien au monde"),
    36: ("Sainte-Sophie", "Ancienne basilique byzantine puis mosquée ottomane à Istanbul"),
    37: ("la Laure des Grottes de Kiev", "Monastère orthodoxe aux coupoles dorées"),

    38: ("la Casbah d'Alger", "Quartier historique fortifié surplombant la baie d'Alger"),
    39: ("les palais royaux d'Abomey", "Palais en terre des rois du royaume du Dahomey"),
    40: ("les ruines de Loropéni", "Forteresse en pierre liée au commerce transsaharien de l'or"),
    41: ("le palais royal de Foumban", "Siège du royaume Bamoun, construit en 1917"),
    42: ("le Karthala", "Volcan actif de Grande Comore à l'un des plus grands cratères du monde"),
    43: ("le parc national d'Odzala-Kokoua", "L'un des plus anciens parcs d'Afrique, réputé pour ses gorilles"),
    44: ("la basilique Notre-Dame de la Paix", "Plus grande basilique du monde par sa superficie, à Yamoussoukro"),
    45: ("le lac Assal", "Point le plus bas d'Afrique, lac hypersalé entouré de laves noires"),
    46: ("les pyramides de Gizeh", "Dont la grande pyramide de Khéops, dernière merveille du monde antique"),
    47: ("le parc national de la Lopé", "Forêts et savanes classées UNESCO, gravures rupestres préhistoriques"),
    48: ("le massif du Fouta Djalon", "« Château d'eau de l'Afrique de l'Ouest », falaises et cascades"),
    49: ("Leptis Magna", "Cité antique romaine remarquablement conservée sur la côte"),
    50: ("l'allée des Baobabs", "Alignement spectaculaire de baobabs centenaires près de Morondava"),
    51: ("la Grande Mosquée de Djenné", "Plus grand édifice en terre crue au monde"),
    52: ("les Terres des Sept Couleurs", "Dunes de sable volcanique multicolore à Chamarel"),
    53: ("Chinguetti", "Cité caravanière du désert, « Sorbonne du désert », septième ville sainte de l'Islam"),
    54: ("la médina de Fès", "Plus grande zone piétonne du monde, centre historique classé UNESCO"),
    55: ("la Grande Mosquée d'Agadez", "Plus haute structure en terre crue du monde (minaret de 27 m)"),
    56: ("le parc national impénétrable de Bwindi", "Abrite près de la moitié des gorilles de montagne survivants"),
    57: ("la réserve de Dzanga-Sangha", "Clairière où se rassemblent chaque jour des dizaines d'éléphants de forêt"),
    58: ("le parc national des Virunga", "Plus ancien parc d'Afrique, seul site avec trois espèces de grands singes"),
    59: ("l'île de Gorée", "Ancien comptoir de la traite négrière au large de Dakar"),
    60: ("la Vallée de Mai", "Forêt primaire abritant le coco de mer, plus grosse graine du monde"),
    61: ("la Guelta d'Archei", "Oasis rocheuse de l'Ennedi, dernière population de crocodiles du désert"),
    62: ("le Koutammakou", "« Pays des Batammariba », cases-tours en terre appelées Takienta"),
    63: ("l'amphithéâtre d'El Jem", "L'un des plus grands amphithéâtres romains au monde"),
    64: ("les chutes Victoria", "L'une des plus grandes chutes d'eau du monde, sur le Zambèze"),

    65: ("les Bouddhas de Bamiyan", "Statues monumentales sculptées au VIe siècle, détruites en 2001"),
    66: ("le Jamdani", "Tissage traditionnel de mousseline de coton brodée à la main"),
    67: ("la mosquée Sultan Omar Ali Saifuddien", "Dôme doré et colonnes de marbre italien, achevée en 1958"),
    68: ("Angkor Vat", "Le plus grand complexe religieux du monde, temple khmer du XIIe siècle"),
    69: ("la Grande Muraille", "Fortification de plusieurs milliers de kilomètres"),
    70: ("le kimchi", "Chou fermenté épicé, spécialité culinaire quotidienne coréenne"),
    71: ("le Taj Mahal", "Mausolée de marbre blanc construit à Agra au XVIIe siècle"),
    72: ("Borobudur", "Le plus grand temple bouddhiste du monde, à Java"),
    73: ("Persépolis", "Cité cérémonielle de l'Empire perse achéménide"),
    74: ("le Mont Fuji", "Plus haut sommet du Japon, volcan sacré et symbole national"),
    75: ("la tour Baïterek", "Tour d'observation surmontée d'une sphère dorée, à Astana"),
    76: ("la tour Bourana", "Ancien minaret du XIe siècle vestige de la Route de la Soie"),
    77: ("le That Luang", "Grand stupa bouddhiste doré, monument national du Laos"),
    78: ("les tours Petronas", "Gratte-ciel jumeaux de 452 m à Kuala Lumpur"),
    79: ("la statue équestre de Gengis Khan", "Statue en acier de 40 m, la plus grande statue équestre du monde"),
    80: ("la pagode Shwedagon", "Stupa bouddhiste recouvert de feuilles d'or à Yangon"),
    81: ("l'Everest", "Plus haut sommet du monde, à la frontière Népal-Tibet"),
    82: ("les ruines de Mohenjo-daro", "Cité antique de la civilisation de la vallée de l'Indus"),
    83: ("les rizières de Banaue", "Terrasses agricoles sculptées il y a environ 2000 ans"),
    84: ("le Merlion", "Statue mi-lion mi-poisson à Marina Bay, symbole de Singapour"),
    85: ("le Taipei 101", "Gratte-ciel de 508 m, longtemps le plus haut bâtiment du monde"),
    86: ("le Wat Arun", "Temple de l'Aube orné de porcelaine, sur le fleuve Chao Phraya"),
    87: ("la Porte de l'Enfer", "Cratère gazier en combustion continue depuis 1971, désert du Karakoum"),
    88: ("la baie d'Halong", "Baie parsemée de près de 2000 îlots karstiques"),

    89: ("les chutes d'Iguazu", "Ensemble de 275 cascades à la frontière avec le Brésil"),
    90: ("le Salar de Uyuni", "Plus grand désert de sel du monde, effet miroir après la pluie"),
    91: ("les chutes du Niagara", "Spectaculaires chutes d'eau à la frontière avec les États-Unis"),
    92: ("les Moaï de l'île de Pâques", "Statues monumentales du peuple Rapa Nui"),
    93: ("la cathédrale de Sel de Zipaquirá", "Église souterraine sculptée dans une ancienne mine de sel"),
    94: ("le volcan Arenal", "L'un des volcans les plus emblématiques d'Amérique centrale"),
    95: ("les cigares cubains (Habanos)", "Spécialité artisanale roulée à la main, région de Viñales"),
    96: ("les îles Galápagos", "Archipel volcanique à la faune endémique qui a inspiré Darwin"),
    97: ("la Statue de la Liberté", "Offerte par la France, à l'entrée du port de New York"),
    98: ("Tikal", "Ancienne cité maya dans la jungle, temples-pyramides"),
    99: ("la Citadelle Laferrière", "Plus grande forteresse des Amériques, construite par Henri Christophe"),
    100: ("Chichén Itzá", "Cité maya-toltèque célèbre pour sa pyramide El Castillo"),
    101: ("les ruines jésuites de Trinidad", "Vestiges d'une mission jésuite du XVIIIe siècle"),
    102: ("le Machu Picchu", "Cité inca perchée dans les Andes péruviennes"),
    103: ("la Zone coloniale de Saint-Domingue", "Premier centre urbain européen des Amériques"),
    104: ("« La Mano »", "Sculpture d'une main enfoncée dans le sable, à Punta del Este"),
    105: ("le Salto Ángel", "Plus haute chute d'eau du monde (979 m), parc national Canaima"),

    106: ("l'Opéra de Sydney", "Célèbre bâtiment aux voiles blanches en forme de coquillages"),
    107: ("le bougna", "Plat traditionnel kanak cuit à l'étouffée sous des pierres chaudes"),
    108: ("Milford Sound", "Fjord du Fiordland aux falaises abruptes et à la cascade Stirling Falls"),
    109: ("le poisson cru au lait de coco", "Thon cru mariné au citron vert et au lait de coco, plat emblématique de Tahiti"),
    110: ("le volcan Yasur", "Volcan actif de l'île de Tanna, surnommé « le phare du Pacifique »"),
    111: ("la cathédrale Notre-Dame de l'Assomption", "Construite en pierre de lave et corail à Mata-Utu"),

    # Ajoutés le 2026-07-15
    112: ("le Christ Rédempteur", "Statue monumentale du Christ dominant Rio de Janeiro depuis le sommet du Corcovado"),
    113: ("le mur des Lamentations", "Vestige du second Temple de Jérusalem, lieu de prière et de pèlerinage parmi les plus visités au monde"),
    114: ("les ruines de Baalbek", "Vaste complexe de temples romains antiques, l'un des mieux conservés au monde"),
}
