# -*- coding: utf-8 -*-
# Deuxième monument/site touristique/spécialité locale, un par pays,
# DIFFÉRENT de celui déjà utilisé dans quiz_monuments_facts.py. Recherché
# par agents web (voir RECHERCHE_2E_MONUMENT_SPECIALITE.md pour les
# sources). Clé = tier. Valeur = (nom_court, description_complète), même
# format que MONUMENTS dans quiz_monuments_facts.py.
#
# Remplace la question "sur quel continent ?" (jugée trop facile), en
# évitant toute duplication avec la question monument/spécialité déjà
# existante.

SECOND_MONUMENTS = {
    # --- Europe ---
    0: ("la porte de Brandebourg", "Monument néoclassique de Berlin, ancien symbole de la division puis de la réunification allemande"),
    1: ("la Casa de la Vall", "Siège du parlement andorran de 1702 à 2011, l'un des plus anciens parlements d'Europe, avec son « armoire aux sept clés »"),
    2: ("Big Ben", "Surnom de la cloche de la tour Elizabeth du Palais de Westminster à Londres"),
    4: ("le Sachertorte", "Gâteau au chocolat viennois créé en 1832, spécialité emblématique de Vienne"),
    5: ("l'Atomium", "Structure monumentale de Bruxelles construite pour l'Exposition universelle de 1958"),
    6: ("la vallée des Roses", "Région autour de Kazanlak, premier producteur mondial d'huile de rose"),
    7: ("les jardins de Tivoli", "Parc d'attractions de Copenhague ouvert en 1843, qui inspira Walt Disney"),
    8: ("le château d'Édimbourg", "Forteresse dominant la capitale écossaise, l'un des monuments les plus visités du Royaume-Uni"),
    9: ("l'Alhambra de Grenade", "Palais et forteresse maure classé au patrimoine mondial de l'UNESCO"),
    10: ("le Laulupidu", "Grand festival de chant estonien, tradition inscrite au patrimoine immatériel de l'UNESCO, qui joua un rôle dans la « Révolution chantante »"),
    11: ("la forteresse de Suomenlinna", "Citadelle maritime du XVIIIe siècle à Helsinki, classée UNESCO"),
    12: ("le Mont-Saint-Michel", "Îlot rocheux couronné par une abbaye médiévale, en Normandie"),
    13: ("Hauteville House", "Demeure de Victor Hugo à Saint-Pierre-Port, où il écrivit une partie des Misérables en exil"),
    14: ("les bains Széchenyi", "L'un des plus grands complexes thermaux d'Europe, à Budapest"),
    15: ("Newgrange", "Monument mégalithique du néolithique, plus ancien que Stonehenge et les pyramides de Gizeh"),
    16: ("la tour de Pise", "Campanile penché de la cathédrale de Pise"),
    17: ("le château de Mont Orgueil", "Forteresse médiévale surplombant le port de Gorey"),
    18: ("la vieille ville de Riga", "Quartier classé UNESCO, réputé pour sa densité de bâtiments Art nouveau"),
    19: ("la colline des Croix", "Site de pèlerinage près de Šiauliai réunissant des dizaines de milliers de croix"),
    20: ("le palais grand-ducal", "Résidence officielle du Grand-Duc, au cœur de la vieille ville de Luxembourg"),
    21: ("le Grand Prix de Monaco", "Course de Formule 1 disputée dans les rues de la Principauté depuis 1929"),
    22: ("les stavkirker", "Églises en bois debout médiévales, comme celle d'Urnes, classée UNESCO"),
    23: ("le parc floral de Keukenhof", "Plus grand jardin de fleurs du monde, célèbre pour ses tulipes"),
    24: ("Llanfairpwllgwyngyll", "Village de l'île d'Anglesey portant le nom de lieu le plus long d'Europe (58 lettres)"),
    25: ("les mines de sel de Wieliczka", "Mine médiévale classée UNESCO, avec des chapelles sculptées dans le sel"),
    26: ("le palais de Pena", "Palais romantique coloré perché sur les collines de Sintra, classé UNESCO"),
    27: ("le palais du Parlement", "Bâtiment administratif civil le plus lourd et l'un des plus vastes du monde, à Bucarest"),
    28: ("la cathédrale Saint-Basile-le-Bienheureux", "Édifice orthodoxe aux bulbes colorés sur la place Rouge à Moscou"),
    29: ("les timbres-poste saint-marinais", "Production philatélique prisée des collectionneurs du monde entier, importante source de revenus du pays"),
    30: ("le monastère de Studenica", "Monastère orthodoxe médiéval classé UNESCO"),
    31: ("le château de Spiš", "L'un des plus grands complexes castraux d'Europe centrale, classé UNESCO"),
    32: ("les grottes de Postojna", "L'un des plus grands réseaux de grottes karstiques d'Europe, visitées en petit train depuis 1872"),
    33: ("l'Icehotel de Jukkasjärvi", "Premier hôtel de glace au monde, reconstruit chaque hiver"),
    34: ("le Jungfraujoch", "« Top of Europe », plus haute gare ferroviaire d'Europe, dans les Alpes bernoises"),
    35: ("l'horloge astronomique de Prague", "Installée en 1410, la plus ancienne horloge astronomique encore en fonctionnement"),
    37: ("le bortsch ukrainien", "Soupe traditionnelle à la betterave, inscrite en 2022 au patrimoine culturel immatériel de l'UNESCO en sauvegarde urgente"),

    # --- Asie ---
    3: ("le monastère de Guéghard", "Complexe monastique du XIIIe siècle, en partie taillé à même la roche, classé UNESCO"),
    36: ("Pamukkale", "Vasques et terrasses de calcaire blanc formées par des sources chaudes, site UNESCO en Anatolie"),
    65: ("le Minaret de Jam", "Tour en briques cuites du XIIe siècle, haute de 65 m, premier site afghan classé UNESCO"),
    66: ("les Sundarbans", "Plus grande forêt de mangrove au monde, dans le delta du Gange, classée UNESCO, refuge du tigre du Bengale"),
    67: ("Kampong Ayer", "Plus grand village sur pilotis au monde, environ 30 000 habitants sur la rivière Brunei"),
    68: ("le temple de Preah Vihear", "Sanctuaire khmer dédié à Shiva, perché sur une falaise à la frontière thaïlandaise, classé UNESCO"),
    69: ("l'Armée de terre cuite de Xi'an", "Des milliers de statues de soldats en terre cuite gardant le tombeau du premier empereur Qin"),
    70: ("le palais Gyeongbokgung", "Principal palais royal de la dynastie Joseon, construit en 1395 à Séoul"),
    71: ("le Fort Rouge de Delhi", "Forteresse moghole en grès rouge du XVIIe siècle, résidence des empereurs moghols, classée UNESCO"),
    72: ("le temple de Prambanan", "Le plus grand complexe de temples hindous d'Indonésie, site UNESCO près de Yogyakarta"),
    73: ("la place Naghsh-e Jahan", "Immense place royale du XVIIe siècle à Ispahan, classée UNESCO"),
    74: ("le château de Himeji", "Le plus grand château féodal japonais conservé, surnommé « château du Héron blanc », classé UNESCO"),
    75: ("le mausolée de Khoja Ahmed Yasavi", "Bâti sur ordre de Tamerlan entre 1389 et 1405 à Turkestan, chef-d'œuvre inachevé de l'architecture timouride, UNESCO"),
    76: ("le lac Issyk-Koul", "Deuxième plus grand lac alpin du monde, ne gèle jamais malgré son altitude de 1607 m"),
    77: ("la Plaine des Jarres", "Site mégalithique de Xieng Khouang parsemé de milliers de jarres de pierre datant de l'âge du fer"),
    78: ("les grottes de Batu", "Sanctuaire hindou dans des grottes calcaires près de Kuala Lumpur, avec une statue géante de Murugan"),
    79: ("le monastère d'Erdene Zuu", "Premier monastère bouddhiste de Mongolie, fondé en 1585 près de Kharkhorin"),
    80: ("Bagan", "Ancienne capitale de royaume, plaine parsemée de plus de 2000 temples et pagodes bouddhiques des XIe-XIIIe siècles"),
    81: ("Lumbini", "Lieu de naissance de Bouddha, site de pèlerinage bouddhiste classé UNESCO"),
    82: ("la mosquée Badshahi", "Construite en 1673 par l'empereur moghol Aurangzeb à Lahore, l'une des plus grandes mosquées du monde"),
    83: ("les Chocolate Hills", "Plus de 1200 collines coniques calcaires de Bohol qui brunissent en saison sèche"),
    84: ("Gardens by the Bay", "Parc futuriste avec les « Supertrees », structures verticales végétalisées de la baie de Marina"),
    85: ("le bubble tea", "Boisson à base de thé et perles de tapioca, inventée à Taïwan dans les années 1980"),
    86: ("le parc historique d'Ayutthaya", "Ruines de l'ancienne capitale du royaume siamois, détruite par les Birmans en 1767, classé UNESCO"),
    87: ("le cheval Akhal-Teke", "Race chevaline ancienne de plus de 3000 ans, symbole national figurant sur les armoiries du Turkménistan"),
    88: ("la vieille ville de Hoi An", "Ancien port marchand du XVe-XIXe siècle, quartier historique classé UNESCO sur la côte centrale du Vietnam"),

    # --- Afrique ---
    38: ("Timgad", "Cité romaine fondée par Trajan en 100 apr. J.-C., exemple d'urbanisme en damier, ensevelie sous le sable pendant 1000 ans, UNESCO"),
    39: ("la Porte du Non-Retour d'Ouidah", "Arche mémorielle marquant le point d'embarquement des esclaves vers les Amériques"),
    40: ("la Grande Mosquée de Bobo-Dioulasso", "Mosquée en banco construite vers 1880 en style soudano-sahélien, la plus ancienne encore en usage du pays"),
    41: ("le mont Cameroun", "Volcan actif de 4095 m, plus haut sommet d'Afrique de l'Ouest et d'Afrique centrale"),
    42: ("la Grande Mosquée du Vendredi de Moroni", "Mosquée historique du quartier Badjanani, autour de laquelle la capitale s'est développée"),
    43: ("la basilique Sainte-Anne-du-Congo", "Basilique au toit de tuiles vertes construite en 1943-1949 à Brazzaville, mémorial de la France Libre"),
    44: ("la ville historique de Grand-Bassam", "Ancienne première capitale coloniale du pays, classée UNESCO pour son architecture coloniale et son village de pêcheurs N'zima"),
    45: ("le lac Abbé", "Cheminées naturelles de calcaire de plusieurs dizaines de mètres, formées par des fumerolles, dans un paysage lunaire"),
    46: ("le temple d'Abou Simbel", "Temple monumental creusé dans la roche par Ramsès II, déplacé pierre par pierre dans les années 1960"),
    47: ("le parc national de Loango", "Célèbre pour ses « hippopotames surfeurs » photographiés sur la plage, où éléphants et gorilles se promènent aussi sur le sable"),
    48: ("le mont Nimba", "Réserve naturelle intégrale classée UNESCO à cheval sur la Guinée, le Liberia et la Côte d'Ivoire"),
    49: ("la vieille ville de Ghadamès", "« Perle du désert », cité pré-saharienne aux maisons superposées reliées par des ruelles couvertes, UNESCO"),
    50: ("les Tsingy de Bemaraha", "Formations karstiques calcaires en aiguilles acérées, parc national classé UNESCO"),
    51: ("la falaise de Bandiagara", "Escarpement gréseux de 200 km abritant 289 villages dogons, greniers et cases à toits pointus, UNESCO"),
    52: ("Le Morne Brabant", "Montagne péninsulaire ayant servi de refuge aux esclaves marrons aux XVIIIe-XIXe siècles, symbole de résistance, UNESCO"),
    53: ("la structure de Richat", "« Œil du Sahara », dôme rocheux circulaire de 40 à 50 km de diamètre visible depuis l'espace"),
    54: ("le Jardin Majorelle", "Jardin exotique créé par le peintre Jacques Majorelle à Marrakech, racheté et restauré par Yves Saint Laurent"),
    55: ("la réserve naturelle de l'Aïr et du Ténéré", "L'une des plus grandes aires protégées d'Afrique, massif montagneux et désert, UNESCO"),
    56: ("les tombeaux des rois du Buganda à Kasubi", "Mausolée royal circulaire construit en 1882 en matériaux végétaux, lieu spirituel du royaume baganda, UNESCO"),
    57: ("le parc national Manovo-Gounda St Floris", "Plus grand parc des savanes d'Afrique centrale, abritant rhinocéros noirs et éléphants, UNESCO"),
    58: ("la réserve de faune à okapis", "Forêt de l'Ituri abritant environ 5000 okapis sauvages et les peuples pygmées Mbuti et Efe, UNESCO"),
    59: ("le lac Rose", "Lagune à la couleur rose due à l'algue Dunaliella salina, salinité supérieure à celle de la mer Morte"),
    60: ("l'atoll d'Aldabra", "Plus grand récif corallien surélevé du monde, abritant environ 100 000 à 150 000 tortues géantes, UNESCO"),
    61: ("le parc national de Zakouma", "Plus ancien parc national du Tchad, population d'éléphants remontée d'environ 450 à près de 800 grâce à la lutte anti-braconnage"),
    62: ("le marché des féticheurs d'Akodessewa", "Plus grand marché vaudou au monde, à Lomé, installé en 1946"),
    63: ("la médina de Tunis", "L'une des premières villes arabo-musulmanes du Maghreb, fondée en 698 autour de la mosquée Zitouna, UNESCO"),
    64: ("le parc national de South Luangwa", "Considéré comme le berceau du safari à pied, popularisé dans les années 1950 par Norman Carr"),

    # --- Amérique ---
    89: ("le glacier Perito Moreno", "Glacier du parc national Los Glaciares en Patagonie, l'un des rares glaciers au monde encore en expansion"),
    90: ("le site archéologique de Tiwanaku", "Cité précolombienne près du lac Titicaca, capitale d'un empire andin, apogée entre 500 et 900 apr. J.-C., UNESCO"),
    91: ("le sirop d'érable", "Le Canada, et surtout le Québec, produit plus de 70% du sirop d'érable mondial"),
    92: ("le parc national Torres del Paine", "Massif de trois célèbres tours de granite en Patagonie chilienne, réserve de biosphère UNESCO"),
    93: ("la ville fortifiée de Carthagène des Indes", "Centre historique colonial ceint de remparts de 11 km construits dès 1586, classé UNESCO"),
    94: ("la réserve de forêt nuageuse de Monteverde", "Forêt tropicale d'altitude d'une biodiversité exceptionnelle, plus de 400 espèces d'oiseaux dont le quetzal resplendissant"),
    95: ("La Havane Vieille", "Centre historique colonial de La Havane, architecture baroque et néoclassique, classé UNESCO"),
    96: ("le chapeau « Panama » de Montecristi", "Chapeau tissé à la main en paille toquilla, en réalité originaire d'Équateur et non du Panama"),
    97: ("le Grand Canyon", "Immense gorge creusée par le fleuve Colorado en Arizona, l'un des sites naturels les plus visités au monde"),
    98: ("Antigua Guatemala", "Ancienne capitale coloniale espagnole fondée en 1543, célèbre pour son architecture baroque, classée UNESCO"),
    99: ("le Palais Sans-Souci", "Résidence royale du roi Henri Christophe construite entre 1810 et 1813 à Milot, surnommée le « Versailles des Caraïbes »"),
    100: ("la tequila", "Spiritueux issu de l'agave bleue, produit exclusivement dans la région de Jalisco, paysage agavier classé UNESCO"),
    101: ("le barrage d'Itaipu", "Barrage hydroélectrique binational Paraguay-Brésil, l'un des plus puissants au monde, fournissant près de 90% de l'électricité du Paraguay"),
    102: ("les lignes de Nazca", "Immenses géoglyphes tracés dans le désert de Nazca entre 500 av. J.-C. et 500 apr. J.-C., classés UNESCO"),
    103: ("le larimar", "Pierre semi-précieuse bleue rarissime, variété de pectolite trouvée uniquement près de Barahona, en République Dominicaine"),
    104: ("le quartier historique de Colonia del Sacramento", "Ville fondée par les Portugais en 1680, mélange unique d'urbanisme portugais, espagnol et postcolonial, UNESCO"),
    105: ("les éclairs du Catatumbo", "Phénomène orageux quasi permanent au-dessus du lac de Maracaibo, zone à la plus forte densité d'éclairs au monde"),

    # --- Océanie ---
    106: ("la Grande Barrière de Corail", "Le plus grand récif corallien du monde, plus de 2300 km au large du Queensland, classé UNESCO"),
    107: ("le lagon de Nouvelle-Calédonie", "Deuxième plus grand récif corallien continu au monde après celui d'Australie, ses lagons inscrits UNESCO en 2008"),
    108: ("le Hobbiton Movie Set", "Village du Comté des films Le Seigneur des Anneaux et Le Hobbit, conservé comme décor permanent près de Matamata"),
    109: ("le marae Taputapuatea", "Ancien centre cérémoniel et politique majeur de la civilisation polynésienne, sur l'île de Raiatea, classé UNESCO"),
    110: ("le saut du Gol", "Rituel initiatique de l'île de Pentecôte : des hommes sautent d'une tour en bois de 20 à 30 mètres retenus aux chevilles par des lianes"),
    111: ("le site de Talietumu", "Forteresse fortifiée bâtie vers le milieu du XVe siècle en pierre volcanique par la noblesse tongienne"),

    # Ajoutés le 2026-07-15
    112: ("les chutes d'Iguaçu", "Impressionnantes chutes d'eau à la frontière du Brésil et de l'Argentine, parmi les plus larges au monde"),
    113: ("la mer Morte", "Lac salé bordant Israël et la Jordanie, point le plus bas de la surface terrestre"),
    114: ("les cèdres du Liban", "Arbre emblématique figurant sur le drapeau libanais, autrefois exploité pour la construction navale phénicienne"),
}
