function init(self)
	sound.play("VoiceSound#ReadyToGo")
	self.timeLeft=6
	finalScore=0
	level=0
	score=0
	bonusHitted=0
	oldLevel=-1
	posInLevel = 1
	
end

function update(self, dt)
	if self.timeLeft > 0 then
		self.timeLeft = math.max(self.timeLeft - dt, 0)
		label.set_text("readyToGo#label", string.format("%.0f", tostring(self.timeLeft)))
	else
		level=0
		msg.post("main:/loader#main", "changeScene", { newScene = "sceneInfo" })
	end
end
