local frequency = 0.5
local bonus_prob = 0.2
local min_y = 60
local max_y = 600

function init(self)
	self.timer = 1/frequency	
	math.randomseed(0)
end

function update(self, dt)
	self.timer = self.timer - dt
	if self.timer <= 0 then
		self.timer = 1/frequency
		local p = go.get_position()
		p.y = 900
		p.x = -100
		if math.random() < bonus_prob then
			component = "#BonusFactory"
			factory.create(component, p)
		end
		
	end
end